# Add Travis CI - February 2021
dist: xenial
language: r
warnings_are_errors: true
sudo: required
cache: packages

r_packages:
  - readr
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
