# cpsR
# cps_variables
# Author:  Daniel Navarrete <https://github.com/navarretedaniel>
# 2019

# Introduction -----------------------------------------------------------------
#
# For a given year, define column widths and variable names for CPS'
# fixed-width delimited data structure.

# Objects- ---------------------------------------------------------------------
# Define CPS Variables for each survey year.

  if (input_year == 18){  
    widths_18 <- c(15,3,4,3,3,3,3,3,3,3,3,3,3,3,8,3,3,3,3,3,3,3,5,3,3,3,3,3,3,3,3,3,4,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                   3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                   3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,8,8,8,8,3,3,8,3,8,8,3,3,3,3,3,
                   3,3,3,3,3,3,3,3,8,8,8,8,8,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                   3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,5,2,3,3,3,3,3,3,8,4,4,4,4,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                   3,3,3,3,3,3,3,3,3,3,4,3,4,3,3,3,3,3,3,3,3,4,3,3,3,3,3,4,4,3,3,3,3,3,3,3,3,3,3,3,3,3,4,3,3,3,3,3,3,4,4,3,3,3,4,3,4,3,3,4,3,3,3,3,3,3,3,4,3,4,3,3,3,3,3,3,3,3,
                   8,3,8,4,4,3)
    
    names_18 <- c("hrhhid","hrmonth","hryear4","hurespli","hufinal","hetenure","hehousut","hetelhhd","hetelavl","hephoneo","hefaminc","hutypea","hutypb","hutypc","hwhhwgt",
                  "hrintsta","hrnumhou","hrhtype","hrmis","huinttyp","huprscnt","hrlonglk","hrhhid2","hwhhwtln","hubus","hubusl1","hubusl2","hubusl3","hubusl4","gereg","gediv",
                  "gestfips","gtcbsa","gtco","gtcbsast","gtmetsta","gtindvpc","gtcbsasz","gtcsa","perrp","peparent","prtage","prtfage","pemaritl","pespouse","pesex","peafever",
                  "peafnow","peeduca","ptdtrace","prdthsp","puchinhh","pulineno","prfamnum","prfamrel","prfamtyp","pehspnon","prmarsta","prpertyp","penatvty","pemntvty",
                  "pefntvty","prcitshp","prcitflg","prinusyr","puslfprx","pemlr","puwk","pubus1","pubus2ot","pubusck1","pubusck2","pubusck3","pubusck4","puretot","pudis",
                  "peret1","pudis1","pudis2","puabsot","pulay","peabsrsn","peabspdo","pemjot","pemjnum","pehrusl1","pehrusl2","pehrftpt","pehruslt","pehrwant","pehrrsn1",
                  "pehrrsn2","pehrrsn3","puhroff1","puhroff2","puhrot1","puhrot2","pehract1","pehract2","pehractt","pehravl","puhrck1","puhrck2","puhrck3","puhrck4","puhrck5",
                  "puhrck6","puhrck7","puhrck12","pulaydt","pulay6m","pelayavl","pulayavr","pelaylk","pelaydur","pelayfto","pulayck1","pulayck2","pulayck3","pulk","pelkm1",
                  "pulkm2","pulkm3","pulkm4","pulkm5","pulkm6","pulkdk1","pulkdk2","pulkdk3","pulkdk4","pulkdk5","pulkdk6","pulkps1","pulkps2","pulkps3","pulkps4","pulkps5",
                  "pulkps6","pelkavl","pulkavr","pelkll1o","pelkll2o","pelklwo","pelkdur","pelkfto","pedwwnto","pedwrsn","pedwlko","pedwwk","pedw4wk","pedwlkwk","pedwavl",
                  "pedwavr","pudwck1","pudwck2","pudwck3","pudwck4","pudwck5","pejhwko","pujhdp1o","pejhrsn","pejhwant","pujhck1","pujhck2","prabsrea","prcivlf","prdisc",
                  "premphrs","prempnot","prexplf","prftlf","prhrusl","prjobsea","prpthrs","prptrea","prunedur","pruntype","prwksch","prwkstat","prwntjob","pujhck3","pujhck4",
                  "pujhck5","puiodp1","puiodp2","puiodp3","peio1cow","puio1mfg","peio2cow","puio2mfg","puiock1","puiock2","puiock3","prioelg","pragna","prcow1","prcow2",
                  "prcowpg","prdtcow1","prdtcow2","prdtind1","prdtind2","prdtocc1","prdtocc2","premp","prmjind1","prmjind2","prmjocc1","prmjocc2","prmjocgr","prnagpws",
                  "prnagws","prsjmj","prerelg","peernuot","peernper","peernrt","peernhry","puernh1c","peernh2","peernh1o","prernhly","pthr","peernhro","prernwa","ptwk","peern",
                  "puern2","ptot","peernwkp","peernlab","peerncov","penlfjh","penlfret","penlfact","punlfck1","punlfck2","peschenr","peschft","peschlvl","prnlfsch","pwfmwgt",
                  "pwlgwgt","pworwgt","pwsswgt","pwvetwgt","prchld","prnmchld","pxpdemp1","prwernal","prhernal","hxtenure","hxhousut","hxtelhhd","hxtelavl","hxphoneo",
                  "pxinusyr","pxrrp","pxparent","pxage","pxmaritl","pxspouse","pxsex","pxafwhn1","pxafnow","pxeduca","pxrace1","pxnatvty","pxmntvty","pxfntvty","pxnmemp1",
                  "pxhspnon","pxmlr","pxret1","pxabsrsn","pxabspdo","pxmjot","pxmjnum","pxhrusl1","pxhrusl2","pxhrftpt","pxhruslt","pxhrwant","pxhrrsn1","pxhrrsn2","pxhract1",
                  "pxhract2","pxhractt","pxhrrsn3","pxhravl","pxlayavl","pxlaylk","pxlaydur","pxlayfto","pxlkm1","pxlkavl","pxlkll1o","pxlkll2o","pxlklwo","pxlkdur","pxlkfto",
                  "pxdwwnto","pxdwrsn","pxdwlko","pxdwwk","pxdw4wk","pxdwlkwk","pxdwavl","pxdwavr","pxjhwko","pxjhrsn","pxjhwant","pxio1cow","pxio1icd","pxio1ocd","pxio2cow",
                  "pxio2icd","pxio2ocd","pxernuot","pxernper","pxernh1o","pxernhro","pxern","pxpdemp2","pxnmemp2","pxernwkp","pxernrt","pxernhry","pxernh2","pxernlab",
                  "pxerncov","pxnlfjh","pxnlfret","pxnlfact","pxschenr","pxschft","pxschlvl","qstnum","occurnum","pedipged","pehgcomp","pecyc","pxdipged","pxhgcomp","pxcyc",
                  "pwcmpwgt","peio1icd","peio1ocd","peio2icd","peio2ocd","primind1","primind2","peafwhn1","peafwhn2","peafwhn3","peafwhn4","pxafever","pelndad","pelnmom",
                  "pedadtyp","pemomtyp","pecohab","pxlndad","pxlnmom","pxdadtyp","pxmomtyp","pxcohab","pedisear","pediseye","pedisrem","pedisphy","pedisdrs","pedisout",
                  "prdisflg","pxdisear","pxdiseye","pxdisrem","pxdisphy","pxdisdrs","pxdisout","hxfaminc","prdasian","pepdemp1","ptnmemp1","pepdemp2","ptnmemp2","pecert1",
                  "pecert2","pecert3","pxcert1","pxcert2","pxcert3","pesd1","pesd2","pesd3","pesd4","pesd5","pesd6","pescow1","pes1icd","prsdind","pes1ocd","prsdocc","pesd16",
                  "pesd17","ptsd18a","pesd18b","pesd19","pesle1o","pesle2","pesenh1o","ptsenh1o","ptsle4o","pusle5","putsle6","pusle6d","pusern","pusern2","ptsern","ptsern2",
                  "pesle22","pesd20","pesd21","pesd22","pesd23","pesd24","ptsd25","pesd26","pesd27","pesce2o","pesce3","peseh1oa","ptseh1oa","putsce5","ptsce5o","pusce6",
                  "putsce7","pusce8","pusern1","pusern2a","ptsern1","ptsern2a","pesce25","prslwkly","ptslwkly","prscwkly","ptscwkly","peshry","prshr","prsupern","ptst1a",
                  "pest1b","pest3","pest7","pest8","pescow2","pes2icd","prsd2ind","pes2ocd","prsd2occ","pest20","pusd7","pest25","pest26","pest27","pest31","prsupsat",
                  "pwsupwgt","prtensat","pwtenwgt","ptst1tn","ptsd18tn","prdispwk")
  
    } else if (input_year == 17) {
                  widths_17 <- c(15,3,4,3,3,3,3,3,3,3,3,3,3,3,8,3,3,3,3,3,3,3,5,3,3,3,3,3,3,3,3,3,4,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                 3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                 3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                 3,3,3,3,3,3,3,3,8,8,8,8,3,3,8,3,8,8,3,3,3,3,3,3,3,3,3,3,3,3,3,8,8,8,8,8,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                 3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,5,2,3,3,3,3,3,3,8,4,4,4,4,
                                 3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,3,4,3,3,3,3,3,3,3,3,4,3,3,3,3,3,4,4,3,3,
                                 3,3,3,3,3,3,3,3,3,3,3,4,3,3,3,3,3,3,4,4,3,3,3,4,3,4,3,3,4,3,3,3,3,3,3,3,4,3,4,3,3,3,3,3,3,3,3,8,3,8,4,4,3)
  
                  names_17 <- c("hrhhid","hrmonth","hryear4","hurespli","hufinal","hetenure","hehousut","hetelhhd","hetelavl","hephoneo","hefaminc","hutypea","hutypb",
                                "hutypc","hwhhwgt","hrintsta","hrnumhou","hrhtype","hrmis","huinttyp","huprscnt","hrlonglk","hrhhid2","hwhhwtln","hubus","hubusl1","hubusl2",
                                "hubusl3","hubusl4","gereg","gediv","gestfips","gtcbsa","gtco","gtcbsast","gtmetsta","gtindvpc","gtcbsasz","gtcsa","perrp","peparent",
                                "prtage","prtfage","pemaritl","pespouse","pesex","peafever","peafnow","peeduca","ptdtrace","prdthsp","puchinhh","pulineno","prfamnum",
                                "prfamrel","prfamtyp","pehspnon","prmarsta","prpertyp","penatvty","pemntvty","pefntvty","prcitshp","prcitflg","prinusyr","puslfprx","pemlr",
                                "puwk","pubus1","pubus2ot","pubusck1","pubusck2","pubusck3","pubusck4","puretot","pudis","peret1","pudis1","pudis2","puabsot","pulay",
                                "peabsrsn","peabspdo","pemjot","pemjnum","pehrusl1","pehrusl2","pehrftpt","pehruslt","pehrwant","pehrrsn1","pehrrsn2","pehrrsn3","puhroff1",
                                "puhroff2","puhrot1","puhrot2","pehract1","pehract2","pehractt","pehravl","puhrck1","puhrck2","puhrck3","puhrck4","puhrck5","puhrck6",
                                "puhrck7","puhrck12","pulaydt","pulay6m","pelayavl","pulayavr","pelaylk","pelaydur","pelayfto","pulayck1","pulayck2","pulayck3","pulk",
                                "pelkm1","pulkm2","pulkm3","pulkm4","pulkm5","pulkm6","pulkdk1","pulkdk2","pulkdk3","pulkdk4","pulkdk5","pulkdk6","pulkps1","pulkps2",
                                "pulkps3","pulkps4","pulkps5","pulkps6","pelkavl","pulkavr","pelkll1o","pelkll2o","pelklwo","pelkdur","pelkfto","pedwwnto","pedwrsn",
                                "pedwlko","pedwwk","pedw4wk","pedwlkwk","pedwavl","pedwavr","pudwck1","pudwck2","pudwck3","pudwck4","pudwck5","pejhwko","pujhdp1o","pejhrsn",
                                "pejhwant","pujhck1","pujhck2","prabsrea","prcivlf","prdisc","premphrs","prempnot","prexplf","prftlf","prhrusl","prjobsea","prpthrs",
                                "prptrea","prunedur","pruntype","prwksch","prwkstat","prwntjob","pujhck3","pujhck4","pujhck5","puiodp1","puiodp2","puiodp3","peio1cow",
                                "puio1mfg","peio2cow","puio2mfg","puiock1","puiock2","puiock3","prioelg","pragna","prcow1","prcow2","prcowpg","prdtcow1","prdtcow2",
                                "prdtind1","prdtind2","prdtocc1","prdtocc2","premp","prmjind1","prmjind2","prmjocc1","prmjocc2","prmjocgr","prnagpws","prnagws","prsjmj",
                                "prerelg","peernuot","peernper","peernrt","peernhry","puernh1c","peernh2","peernh1o","prernhly","pthr","peernhro","prernwa","ptwk","peern",
                                "puern2","ptot","peernwkp","peernlab","peerncov","penlfjh","penlfret","penlfact","punlfck1","punlfck2","peschenr","peschft","peschlvl",
                                "prnlfsch","pwfmwgt","pwlgwgt","pworwgt","pwsswgt","pwvetwgt","prchld","prnmchld","pxpdemp1","prwernal","prhernal","hxtenure","hxhousut",
                                "hxtelhhd","hxtelavl","hxphoneo","pxinusyr","pxrrp","pxparent","pxage","pxmaritl","pxspouse","pxsex","pxafwhn1","pxafnow","pxeduca","pxrace1",
                                "pxnatvty","pxmntvty","pxfntvty","pxnmemp1","pxhspnon","pxmlr","pxret1","pxabsrsn","pxabspdo","pxmjot","pxmjnum","pxhrusl1","pxhrusl2",
                                "pxhrftpt","pxhruslt","pxhrwant","pxhrrsn1","pxhrrsn2","pxhract1","pxhract2","pxhractt","pxhrrsn3","pxhravl","pxlayavl","pxlaylk","pxlaydur",
                                "pxlayfto","pxlkm1","pxlkavl","pxlkll1o","pxlkll2o","pxlklwo","pxlkdur","pxlkfto","pxdwwnto","pxdwrsn","pxdwlko","pxdwwk","pxdw4wk",
                                "pxdwlkwk","pxdwavl","pxdwavr","pxjhwko","pxjhrsn","pxjhwant","pxio1cow","pxio1icd","pxio1ocd","pxio2cow","pxio2icd","pxio2ocd","pxernuot",
                                "pxernper","pxernh1o","pxernhro","pxern","pxpdemp2","pxnmemp2","pxernwkp","pxernrt","pxernhry","pxernh2","pxernlab","pxerncov","pxnlfjh",
                                "pxnlfret","pxnlfact","pxschenr","pxschft","pxschlvl","qstnum","occurnum","pedipged","pehgcomp","pecyc","pxdipged","pxhgcomp","pxcyc",
                                "pwcmpwgt","peio1icd","peio1ocd","peio2icd","peio2ocd","primind1","primind2","peafwhn1","peafwhn2","peafwhn3","peafwhn4","pxafever","pelndad",
                                "pelnmom","pedadtyp","pemomtyp","pecohab","pxlndad","pxlnmom","pxdadtyp","pxmomtyp","pxcohab","pedisear","pediseye","pedisrem","pedisphy",
                                "pedisdrs","pedisout","prdisflg","pxdisear","pxdiseye","pxdisrem","pxdisphy","pxdisdrs","pxdisout","hxfaminc","prdasian","pepdemp1",
                                "ptnmemp1","pepdemp2","ptnmemp2","pecert1","pecert2","pecert3","pxcert1","pxcert2","pxcert3","pesd1","pesd2","pesd3","pesd4","pesd5","pesd6",
                                "pescow1","pes1icd","prsdind","pes1ocd","prsdocc","pesd16","pesd17","ptsd18a","pesd18b","pesd19","pesle1o","pesle2","pesenh1o","ptsenh1o",
                                "ptsle4o","pusle5","putsle6","pusle6d","pusern","pusern2","ptsern","ptsern2","pesle22","pesd20","pesd21","pesd22","pesd23","pesd24",
                                "ptsd25","pesd26","pesd27","pesce2o","pesce3","peseh1oa","ptseh1oa","putsce5","ptsce5o","pusce6","putsce7","pusce8","pusern1","pusern2a",
                                "ptsern1","ptsern2a","pesce25","prslwkly","ptslwkly","prscwkly","ptscwkly","peshry","prshr","prsupern","ptst1a","pest1b","pest3","pest7",
                                "pest8","pescow2","pes2icd","prsd2ind","pes2ocd","prsd2occ","pest20","pusd7","pest25","pest26","pest27","pest31","prsupsat","pwsupwgt",
                                "prtensat","pwtenwgt","ptst1tn","ptsd18tn","prdispwk")
                  
                  } else if (input_year == 16) {
                          widths_16 <- c(15,3,4,3,3,3,3,3,3,3,3,3,3,3,3,8,3,3,3,3,3,3,3,5,3,3,3,3,3,3,3,3,3,4,3,3,3,3,
                                         3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                         3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                         3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                         3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                         3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,8,8,8,8,3,3,8,3,8,
                                         8,3,3,3,3,3,3,3,3,3,3,3,3,3,8,8,8,8,8,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                         3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                         3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,5,2,3,3,
                                         3,3,3,3,8,4,4,4,4,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                         3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,3,4,3,3,3,3,3,3,3,3,4,3,3,3,3,3,4,4,3,3,3,3,3,
                                         3,3,3,3,3,3,3,3,4,3,3,3,3,3,3,4,4,3,3,3,4,3,4,3,3,4,3,3,3,3,3,3,3,4,3,4,3,3,
                                         3,3,3,3,3,3,8,3,8,4,4,3)
  
                          names_16 <- c("hrhhid","hrmonth","hryear4","hurespli","hufinal","huspnish","hetenure","hehousut",
                                      "hetelhhd","hetelavl","hephoneo","hefaminc","hutypea","hutypb","hutypc","hwhhwgt",
                                      "hrintsta","hrnumhou","hrhtype","hrmis","huinttyp","huprscnt","hrlonglk","hrhhid2",
                                      "hwhhwtln","hubus","hubusl1","hubusl2","hubusl3","hubusl4","gereg","gediv","gestfips",
                                      "gtcbsa","gtco","gtcbsast","gtmetsta","gtindvpc","gtcbsasz","gtcsa","perrp","peparent",
                                      "prtage","prtfage","pemaritl","pespouse","pesex","peafever","peafnow","peeduca","ptdtrace",
                                      "prdthsp","puchinhh","pulineno","prfamnum","prfamrel","prfamtyp","pehspnon","prmarsta",
                                      "prpertyp","penatvty","pemntvty","pefntvty","prcitshp","prcitflg","prinusyr","puslfprx",
                                      "pemlr","puwk","pubus1","pubus2ot","pubusck1","pubusck2","pubusck3","pubusck4","puretot",
                                      "pudis","peret1","pudis1","pudis2","puabsot","pulay","peabsrsn","peabspdo","pemjot","pemjnum",
                                      "pehrusl1","pehrusl2","pehrftpt","pehruslt","pehrwant","pehrrsn1","pehrrsn2","pehrrsn3",
                                      "puhroff1","puhroff2","puhrot1","puhrot2","pehract1","pehract2","pehractt","pehravl","puhrck1",
                                      "puhrck2","puhrck3","puhrck4","puhrck5","puhrck6","puhrck7","puhrck12","pulaydt","pulay6m",
                                      "pelayavl","pulayavr","pelaylk","pelaydur","pelayfto","pulayck1","pulayck2","pulayck3","pulk",
                                      "pelkm1","pulkm2","pulkm3","pulkm4","pulkm5","pulkm6","pulkdk1","pulkdk2","pulkdk3","pulkdk4",
                                      "pulkdk5","pulkdk6","pulkps1","pulkps2","pulkps3","pulkps4","pulkps5","pulkps6","pelkavl",
                                      "pulkavr","pelkll1o","pelkll2o","pelklwo","pelkdur","pelkfto","pedwwnto","pedwrsn","pedwlko",
                                      "pedwwk","pedw4wk","pedwlkwk","pedwavl","pedwavr","pudwck1","pudwck2","pudwck3","pudwck4",
                                      "pudwck5","pejhwko","pujhdp1o","pejhrsn","pejhwant","pujhck1","pujhck2","prabsrea","prcivlf",
                                      "prdisc","premphrs","prempnot","prexplf","prftlf","prhrusl","prjobsea","prpthrs","prptrea",
                                      "prunedur","pruntype","prwksch","prwkstat","prwntjob","pujhck3","pujhck4","pujhck5","puiodp1",
                                      "puiodp2","puiodp3","peio1cow","puio1mfg","peio2cow","puio2mfg","puiock1","puiock2","puiock3",
                                      "prioelg","pragna","prcow1","prcow2","prcowpg","prdtcow1","prdtcow2","prdtind1","prdtind2",
                                      "prdtocc1","prdtocc2","premp","prmjind1","prmjind2","prmjocc1","prmjocc2","prmjocgr","prnagpws",
                                      "prnagws","prsjmj","prerelg","peernuot","peernper","peernrt","peernhry","puernh1c","peernh2",
                                      "peernh1o","prernhly","pthr","peernhro","prernwa","ptwk","peern","puern2","ptot","peernwkp",
                                      "peernlab","peerncov","penlfjh","penlfret","penlfact","punlfck1","punlfck2","peschenr","peschft",
                                      "peschlvl","prnlfsch","pwfmwgt","pwlgwgt","pworwgt","pwsswgt","pwvetwgt","prchld","prnmchld",
                                      "pxpdemp1","prwernal","prhernal","hxtenure","hxhousut","hxtelhhd","hxtelavl","hxphoneo","pxinusyr",
                                      "pxrrp","pxparent","pxage","pxmaritl","pxspouse","pxsex","pxafwhn1","pxafnow","pxeduca","pxrace1",
                                      "pxnatvty","pxmntvty","pxfntvty","pxnmemp1","pxhspnon","pxmlr","pxret1","pxabsrsn","pxabspdo",
                                      "pxmjot","pxmjnum","pxhrusl1","pxhrusl2","pxhrftpt","pxhruslt","pxhrwant","pxhrrsn1","pxhrrsn2",
                                      "pxhract1","pxhract2","pxhractt","pxhrrsn3","pxhravl","pxlayavl","pxlaylk","pxlaydur","pxlayfto",
                                      "pxlkm1","pxlkavl","pxlkll1o","pxlkll2o","pxlklwo","pxlkdur","pxlkfto","pxdwwnto","pxdwrsn","pxdwlko",
                                      "pxdwwk","pxdw4wk","pxdwlkwk","pxdwavl","pxdwavr","pxjhwko","pxjhrsn","pxjhwant","pxio1cow","pxio1icd",
                                      "pxio1ocd","pxio2cow","pxio2icd","pxio2ocd","pxernuot","pxernper","pxernh1o","pxernhro","pxern",
                                      "pxpdemp2","pxnmemp2","pxernwkp","pxernrt","pxernhry","pxernh2","pxernlab","pxerncov","pxnlfjh",
                                      "pxnlfret","pxnlfact","pxschenr","pxschft","pxschlvl","qstnum","occurnum","pedipged","pehgcomp",
                                      "pecyc","pxdipged","pxhgcomp","pxcyc","pwcmpwgt","peio1icd","peio1ocd","peio2icd","peio2ocd","primind1",
                                      "primind2","peafwhn1","peafwhn2","peafwhn3","peafwhn4","pxafever","pelndad","pelnmom","pedadtyp",
                                      "pemomtyp","pecohab","pxlndad","pxlnmom","pxdadtyp","pxmomtyp","pxcohab","pedisear","pediseye",
                                      "pedisrem","pedisphy","pedisdrs","pedisout","prdisflg","pxdisear","pxdiseye","pxdisrem","pxdisphy",
                                      "pxdisdrs","pxdisout","hxfaminc","prdasian","pepdemp1","ptnmemp1","pepdemp2","ptnmemp2","pesd1",
                                      "pesd2","pesd3","pesd4","pesd5","pesd6","pescow1","pes1icd","prsdind","pes1ocd","prsdocc","pesd16",
                                      "pesd17","ptsd18a","pesd18b","pesd19","pesle1o","pesle2","pesenh1o","ptsenh1o","ptsle4o","pusle5",
                                      "putsle6","pusle6d","pusern","pusern2","ptsern","ptsern2","pesle22","pesd20","pesd21","pesd22","pesd23",
                                      "pesd24","ptsd25","pesd26","pesd27","pesce2o","pesce3","peseh1oa","ptseh1oa","putsce5","ptsce5o","pusce6",
                                      "putsce7","pusce8","pusern1","pusern2a","ptsern1","ptsern2a","pesce25","prslwkly","ptslwkly","prscwkly",
                                      "ptscwkly","peshry","prshr","prsupern","ptst1a","pest1b","pest3","pest7","pest8","pescow2","pes2icd",
                                      "prsd2ind","pes2ocd","prsd2occ","pest20","pusd7","pest25","pest26","pest27","pest31","prsupsat",
                                      "pwsupwgt","prtensat","pwtenwgt","ptst1tn","ptsd18tn","prdispwk")
                          
                          } else if (input_year == 15) {
                                      widths_15 <- c(15,3,4,3,3,3,3,3,3,3,3,3,3,3,3,8,3,3,3,3,3,3,3,5,3,3,3,3,3,3,3,3,3,4,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                                     3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                                     3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                                     3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,8,8,8,8,3,3,8,3,8,8,3,3,3,3,3,3,
                                                     3,3,3,3,3,3,3,8,8,8,8,8,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                                     3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,5,2,3,3,3,3,3,3,8,4,4,4,4,3,3
                                                     ,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,3,3,3,3,3,3,3,
                                                     3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                                     3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                                     3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                                     3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,8,8)
  
                                    names_15 <- c("hrhhid","hrmonth","hryear4","hurespli","hufinal","huspnish","hetenure","hehousut","hetelhhd","hetelavl","hephoneo","hefaminc",
                                                  "hutypea","hutypb","hutypc","hwhhwgt","hrintsta","hrnumhou","hrhtype","hrmis","huinttyp","huprscnt","hrlonglk","hrhhid2",
                                                  "hwhhwtln","hubus","hubusl1","hubusl2","hubusl3","hubusl4","gereg","gediv","gestfips","gtcbsa","gtco","gtcbsast","gtmetsta",
                                                  "gtindvpc","gtcbsasz","gtcsa","perrp","peparent","prtage","prtfage","pemaritl","pespouse","pesex","peafever","peafnow",
                                                  "peeduca","ptdtrace","prdthsp","puchinhh","pulineno","prfamnum","prfamrel","prfamtyp","pehspnon","prmarsta","prpertyp",
                                                  "penatvty","pemntvty","pefntvty","prcitshp","prcitflg","prinusyr","puslfprx","pemlr","puwk","pubus1","pubus2ot","pubusck1",
                                                  "pubusck2","pubusck3","pubusck4","puretot","pudis","peret1","pudis1","pudis2","puabsot","pulay","peabsrsn","peabspdo","pemjot",
                                                  "pemjnum","pehrusl1","pehrusl2","pehrftpt","pehruslt","pehrwant","pehrrsn1","pehrrsn2","pehrrsn3","puhroff1","puhroff2","puhrot1",
                                                  "puhrot2","pehract1","pehract2","pehractt","pehravl","puhrck1","puhrck2","puhrck3","puhrck4","puhrck5","puhrck6","puhrck7",
                                                  "puhrck12","pulaydt","pulay6m","pelayavl","pulayavr","pelaylk","pelaydur","pelayfto","pulayck1","pulayck2","pulayck3","pulk",
                                                  "pelkm1","pulkm2","pulkm3","pulkm4","pulkm5","pulkm6","pulkdk1","pulkdk2","pulkdk3","pulkdk4","pulkdk5","pulkdk6","pulkps1",
                                                  "pulkps2","pulkps3","pulkps4","pulkps5","pulkps6","pelkavl","pulkavr","pelkll1o","pelkll2o","pelklwo","pelkdur","pelkfto",
                                                  "pedwwnto","pedwrsn","pedwlko","pedwwk","pedw4wk","pedwlkwk","pedwavl","pedwavr","pudwck1","pudwck2","pudwck3","pudwck4",
                                                  "pudwck5","pejhwko","pujhdp1o","pejhrsn","pejhwant","pujhck1","pujhck2","prabsrea","prcivlf","prdisc","premphrs","prempnot",
                                                  "prexplf","prftlf","prhrusl","prjobsea","prpthrs","prptrea","prunedur","pruntype","prwksch","prwkstat","prwntjob","pujhck3",
                                                  "pujhck4","pujhck5","puiodp1","puiodp2","puiodp3","peio1cow","puio1mfg","peio2cow","puio2mfg","puiock1","puiock2","puiock3",
                                                  "prioelg","pragna","prcow1","prcow2","prcowpg","prdtcow1","prdtcow2","prdtind1","prdtind2","prdtocc1","prdtocc2","premp",
                                                  "prmjind1","prmjind2","prmjocc1","prmjocc2","prmjocgr","prnagpws","prnagws","prsjmj","prerelg","peernuot","peernper","peernrt",
                                                  "peernhry","puernh1c","peernh2","peernh1o","prernhly","pthr","peernhro","prernwa","ptwk","peern","puern2","ptot","peernwkp",
                                                  "peernlab","peerncov","penlfjh","penlfret","penlfact","punlfck1","punlfck2","peschenr","peschft","peschlvl","prnlfsch","pwfmwgt",
                                                  "pwlgwgt","pworwgt","pwsswgt","pwvetwgt","prchld","prnmchld","pxpdemp1","prwernal","prhernal","hxtenure","hxhousut","hxtelhhd",
                                                  "hxtelavl","hxphoneo","pxinusyr","pxrrp","pxparent","pxage","pxmaritl","pxspouse","pxsex","pxafwhn1","pxafnow","pxeduca",
                                                  "pxrace1","pxnatvty","pxmntvty","pxfntvty","pxnmemp1","pxhspnon","pxmlr","pxret1","pxabsrsn","pxabspdo","pxmjot","pxmjnum",
                                                  "pxhrusl1","pxhrusl2","pxhrftpt","pxhruslt","pxhrwant","pxhrrsn1","pxhrrsn2","pxhract1","pxhract2","pxhractt","pxhrrsn3",
                                                  "pxhravl","pxlayavl","pxlaylk","pxlaydur","pxlayfto","pxlkm1","pxlkavl","pxlkll1o","pxlkll2o","pxlklwo","pxlkdur","pxlkfto",
                                                  "pxdwwnto","pxdwrsn","pxdwlko","pxdwwk","pxdw4wk","pxdwlkwk","pxdwavl","pxdwavr","pxjhwko","pxjhrsn","pxjhwant","pxio1cow",
                                                  "pxio1icd","pxio1ocd","pxio2cow","pxio2icd","pxio2ocd","pxernuot","pxernper","pxernh1o","pxernhro","pxern","pxpdemp2","pxnmemp2",
                                                  "pxernwkp","pxernrt","pxernhry","pxernh2","pxernlab","pxerncov","pxnlfjh","pxnlfret","pxnlfact","pxschenr","pxschft","pxschlvl",
                                                  "qstnum","occurnum","pedipged","pehgcomp","pecyc","pxdipged","pxhgcomp","pxcyc","pwcmpwgt","peio1icd","peio1ocd","peio2icd",
                                                  "peio2ocd","primind1","primind2","peafwhn1","peafwhn2","peafwhn3","peafwhn4","pxafever","pelndad","pelnmom","pedadtyp","pemomtyp",
                                                  "pecohab","pxlndad","pxlnmom","pxdadtyp","pxmomtyp","pxcohab","pedisear","pediseye","pedisrem","pedisphy","pedisdrs","pedisout",
                                                  "prdisflg","pxdisear","pxdiseye","pxdisrem","pxdisphy","pxdisdrs","pxdisout","hxfaminc","prdasian","pepdemp1","ptnmemp1",
                                                  "pepdemp2","ptnmemp2","penxtpr","penxtpr3","pea1","pea2","pea2a","pra2b1","pra2c1","pea3","ptb1","peb1a","peb2","peb5anum",
                                                  "peb5aunt","peb5b","peba6a","peb6a","ptb6b","ptb6c","peb6c4","peb6d1","peb6d21","peb6d3","peb6doth","peb6e1","peb6e31",
                                                  "prb6e32a","peb7c","peb7c2","peb7c3","peb8","ptb9","peb10a","ptb10b","pec1","pec1i","ptc1a","pec2","pec5anum","pec5aunt","pec5b",
                                                  "peca6a","pec6a","ptc6b","ptc6c","pec6c4","pec6d1","pec6d21","pec6d3","pec6doth","pec6e1","pec6e31","prc6e32a","pec7a","pec7d",
                                                  "pec7d2","pec7d3","ptc7e","pec8","ptc9","pec10a","ptc10b","peda","pedb","ped1r","ped3","ped3b","ped6num","ped6unt","ped6b",
                                                  "ped6cnum","ped6cunt","ped6c2","ped7r","ped8r","pee1b1","pee1b5","pee1c2","pee1c2b","pee1c2c","pee1c2d1","pee1c2d2","pee1c2d3",
                                                  "pee1cz2c","pef1a","pef1b","peg1","peg2","peg3","peg4","peh1num","peh1unt","peh1b","peh1cnum","peh1cunt","peh2","peh5","pth5a",
                                                  "peh6","pth6a","peh6b","pth6c","peh6c2","peh6c4","peh6c5","peh6e1","peh6e5","peh6fa2","peh6fa2b","peh6fa2c","peh6fa2d1",
                                                  "peh6fa2d2","peh6fa2d3","peh6faz2c","peh61a","peh61b","peh8anum","peh8aunt","peh8b","peh11a","peh11c","peh11d","pej1a1","pej1a2",
                                                  "pej1a3","pej1a3_5","pej1a4","pej1a5","pej2a1","pej2b1","pej2a2","pej2b2","pej2a3","pej2b3","pej2a3_5","pej2b3_5","pej2a4",
                                                  "pej2b4","pej2a5","pej2b5","peja","pejb","pejc","pejnflvin","pejnflvr1","pejnflvr2","pejnflvr3","pejnflv35","pejnflvr4",
                                                  "pejnflvr5","pejecigra","pejecigrb","pejecigrc","pejecigrd","pejd11","pejd21","pejd12","pejd22","pejd13","pejd23","pejd13_5",
                                                  "pejd23_5","pejd14","pejd24","pejd15","pejd25","pejd31","pejd32","pejd33","pejd33_5","pejd34","pejd35","pejfecgra","pejfecgrb",
                                                  "pejfecgrc","pejfecgrd","pej3a1","pej3a2","pej3d","pej3f1","pej3f2","pej3g","pej4","pej6bnum","pej6bunt","pej7b1","pej7b5",
                                                  "pek1a","pek1b","pek1b11","pek1b2","pek1c1","pek2a","pek3a","pek3b","pek3d","pek4","pek5a","pek5b","pek6b","pek6c","pek6g",
                                                  "pek6ga","pek6h","pek6h2","pes78","pesinttp","pes81a","intrview","hrmode","smokstat","prs35","prs60","prs64","prs65","prs66",
                                                  "prj3a1f","prj3df","prj3f1f","prj3gf","prj4f","prj6bnmf","prj7b1f","prsiflg","pwnrwgt","pwsrwgt")
                                    
                                    } else if (input_year == 14) {
                                                  widths_14 <- c(15,3,4,3,3,3,3,3,3,3,3,3,3,3,3,8,3,3,3,3,3,3,3,5,3,3,3,3,3,3,3,3,4,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                                                 3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                                                 3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                                                 3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,8,8,8,8,3,3,8,
                                                                 3,8,8,3,3,3,3,3,3,3,3,3,3,3,3,3,8,8,8,8,8,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                                                                 3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,5,2,3,3,3,3,3,
                                                                 3,3,3,3,3,3,3,8,4,4,4,4,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,3,4,3,3,3,3,
                                                                 3,3,3,3,4,3,3,3,3,3,4,4,3,3,3,3,3,3,3,3,3,3,3,3,3,4,3,3,3,3,3,3,4,4,3,3,3,4,3,4,3,3,4,3,3,3,3,3,3,3,4,3,4,3,3,3,3,
                                                                 3,3,3,3,8,3,8,4,4,3)
                                                  
                                                  names_14 <- c("hrhhid","hrmonth","hryear4","hurespli","hufinal","huspnish","hetenure","hehousut","hetelhhd","hetelavl","hephoneo",
                                                                "hefaminc","hutypea","hutypb","hutypc","hwhhwgt","hrintsta","hrnumhou","hrhtype","hrmis","huinttyp","huprscnt",
                                                                "hrlonglk","hrhhid2","hubus","hubusl1","hubusl2","hubusl3","hubusl4","gereg","gestcen","gestfips","gtcbsa","gtco",
                                                                "gtcbsast","gtmetsta","gtindvpc","gtcbsasz","gtcsa","proldrrp","pupelig","perrp","peparent","prtage","prtfage",
                                                                "pemaritl","pespouse","pesex","peafever","peafnow","peeduca","ptdtrace","prdthsp","puchinhh","pulineno","prfamnum",
                                                                "prfamrel","prfamtyp","pehspnon","prmarsta","prpertyp","penatvty","pemntvty","pefntvty","prcitshp","prcitflg",
                                                                "prinusyr","puslfprx","pemlr","puwk","pubus1","pubus2ot","pubusck1","pubusck2","pubusck3","pubusck4","puretot",
                                                                "pudis","peret1","pudis1","pudis2","puabsot","pulay","peabsrsn","peabspdo","pemjot","pemjnum","pehrusl1","pehrusl2",
                                                                "pehrftpt","pehruslt","pehrwant","pehrrsn1","pehrrsn2","pehrrsn3","puhroff1","puhroff2","puhrot1","puhrot2",
                                                                "pehract1","pehract2","pehractt","pehravl","puhrck1","puhrck2","puhrck3","puhrck4","puhrck5","puhrck6","puhrck7",
                                                                "puhrck12","pulaydt","pulay6m","pelayavl","pulayavr","pelaylk","pelaydur","pelayfto","pulayck1","pulayck2",
                                                                "pulayck3","pulk","pelkm1","pulkm2","pulkm3","pulkm4","pulkm5","pulkm6","pulkdk1","pulkdk2","pulkdk3","pulkdk4",
                                                                "pulkdk5","pulkdk6","pulkps1","pulkps2","pulkps3","pulkps4","pulkps5","pulkps6","pelkavl","pulkavr","pelkll1o",
                                                                "pelkll2o","pelklwo","pelkdur","pelkfto","pedwwnto","pedwrsn","pedwlko","pedwwk","pedw4wk","pedwlkwk","pedwavl",
                                                                "pedwavr","pudwck1","pudwck2","pudwck3","pudwck4","pudwck5","pejhwko","pujhdp1o","pejhrsn","pejhwant","pujhck1",
                                                                "pujhck2","prabsrea","prcivlf","prdisc","premphrs","prempnot","prexplf","prftlf","prhrusl","prjobsea","prpthrs",
                                                                "prptrea","prunedur","pruntype","prwksch","prwkstat","prwntjob","pujhck3","pujhck4","pujhck5","puiodp1","puiodp2",
                                                                "puiodp3","peio1cow","puio1mfg","peio2cow","puio2mfg","puiock1","puiock2","puiock3","prioelg","pragna","prcow1",
                                                                "prcow2","prcowpg","prdtcow1","prdtcow2","prdtind1","prdtind2","prdtocc1","prdtocc2","premp","prmjind1","prmjind2",
                                                                "prmjocc1","prmjocc2","prmjocgr","prnagpws","prnagws","prsjmj","prerelg","peernuot","peernper","peernrt",
                                                                "peernhry","puernh1c","peernh2","peernh1o","prernhly","pthr","peernhro","prernwa","ptwk","peern","puern2","ptot",
                                                                "peernwkp","peernlab","peerncov","penlfjh","penlfret","penlfact","punlfck1","punlfck2","peschenr","peschft",
                                                                "peschlvl","prnlfsch","pwfmwgt","pwlgwgt","pworwgt","pwsswgt","pwvetwgt","prchld","prnmchld","prwernal","prhernal",
                                                                "hxtenure","hxhousut","hxtelhhd","hxtelavl","hxphoneo","pxinusyr","pxrrp","pxparent","pxage","pxmaritl","pxspouse",
                                                                "pxsex","pxafwhn1","pxafnow","pxeduca","pxrace1","pxnatvty","pxmntvty","pxfntvty","pxhspnon","pxmlr","pxret1",
                                                                "pxabspdo","pxmjot","pxmjnum","pxhrusl1","pxhrusl2","pxhrftpt","pxhruslt","pxhrwant","pxhrrsn1","pxhrrsn2",
                                                                "pxhract1","pxhract2","pxhractt","pxhrrsn3","pxhravl","pxlayavl","pxlaylk","pxlaydur","pxlayfto","pxlkm1","pxlkavl",
                                                                "pxlkll1o","pxlkll2o","pxlklwo","pxlkdur","pxlkfto","pxdwwnto","pxdwrsn","pxdwlko","pxdwwk","pxdw4wk","pxdwlkwk",
                                                                "pxdwavl","pxdwavr","pxjhwko","pxjhrsn","pxjhwant","pxio1cow","pxio1icd","pxio1ocd","pxio2cow","pxio2icd",
                                                                "pxio2ocd","pxernuot","pxernper","pxernh1o","pxernhro","pxern","pxernwkp","pxernrt","pxernhry","pxernh2",
                                                                "pxernlab","pxerncov","pxnlfjh","pxnlfret","pxnlfact","pxschenr","pxschft","pxschlvl","qstnum","occurnum",
                                                                "pedipged","pehgcomp","pecyc","pegrprof","pegr6cor","pems123","pxdipged","pxhgcomp","pxcyc","pxgrprof",
                                                                "pxgr6cor","pxms123","pwcmpwgt","peio1icd","peio1ocd","peio2icd","peio2ocd","primind1","primind2","peafwhn1",
                                                                "peafwhn2","peafwhn3","peafwhn4","pxafever","pelndad","pelnmom","pedadtyp","pemomtyp","pecohab","pxlndad",
                                                                "pxlnmom","pxdadtyp","pxmomtyp","pxcohab","pedisear","pediseye","pedisrem","pedisphy","pedisdrs","pedisout",
                                                                "prdisflg","pxdisear","pxdiseye","pxdisrem","pxdisphy","pxdisdrs","pxdisout","hxfaminc","pesd1","pesd2","pesd3",
                                                                "pesd4","pesd5","pesd6","pescow1","pes1icd","prsdind","pes1ocd","prsdocc","pesd16","pesd17","ptsd18a","pesd18b",
                                                                "pesd19","pesle1o","pesle2","pesenh1o","ptsenh1o","ptsle4o","pusle5","putsle6","pusle6d","pusern","pusern2",
                                                                "ptsern","ptsern2","pesle22","pesd20","pesd21","pesd22","pesd23","pesd24","ptsd25","pesd26","pesd27","pesce2o",
                                                                "pesce3","peseh1oa","ptseh1oa","putsce5","ptsce5o","pusce6","putsce7","pusce8","pusern1","pusern2a","ptsern1",
                                                                "ptsern2a","pesce25","prslwkly","ptslwkly","prscwkly","ptscwkly","peshry","prshr","prsupern","ptst1a","pest1b",
                                                                "pest3","pest7","pest8","pescow2","pes2icd","prsd2ind","pes2ocd","prsd2occ","pest20","pusd7","pest25","pest26",
                                                                "pest27","pest31","prsupsat","pwsupwgt","prtensat","pwtenwgt","ptst1tn","ptsd18tn","prdispwk")
                                                  
                                                  } else {
                                                    print("ERROR: Please enter a single year (e.g., 2018) between the year range 2014 - 2019.")
                                                    }
